<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Boyko Amarov">
<meta name="dcterms.date" content="2022-01-04">

<title>Introduction to Time Series Analysis 2023/2024 - 6&nbsp; DF-test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-ARIMA-Forecasting.html" rel="next">
<link href="./05-Model-Fitting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-Unit-Root-Tests.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">DF-test</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Time Series Analysis 2023/2024</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Information</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Statistics-Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistics Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-linear-difference-equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Difference Equations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-AR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Autoregressive Processes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Model-Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ARIMA Modeling (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Unit-Root-Tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">DF-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ARIMA-Forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Forecasting ARIMA processes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-GARCH.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#unit-root-tests" id="toc-unit-root-tests" class="nav-link active" data-scroll-target="#unit-root-tests"><span class="header-section-number">7</span> Unit Root Tests</a>
  <ul class="collapse">
  <li><a href="#random-walks-simulation" id="toc-random-walks-simulation" class="nav-link" data-scroll-target="#random-walks-simulation"><span class="header-section-number">7.1</span> Random Walks Simulation</a></li>
  <li><a href="#how-to-check-for-spurious-regression" id="toc-how-to-check-for-spurious-regression" class="nav-link" data-scroll-target="#how-to-check-for-spurious-regression"><span class="header-section-number">7.2</span> How to check for spurious regression?</a></li>
  </ul></li>
  <li><a href="#unit-root-tests-1" id="toc-unit-root-tests-1" class="nav-link" data-scroll-target="#unit-root-tests-1"><span class="header-section-number">8</span> Unit root tests</a>
  <ul class="collapse">
  <li><a href="#dickey-fuller-unit-root-test" id="toc-dickey-fuller-unit-root-test" class="nav-link" data-scroll-target="#dickey-fuller-unit-root-test"><span class="header-section-number">8.1</span> Dickey-Fuller Unit Root Test</a></li>
  <li><a href="#simulation-2-stationary-ar1-with-zero-level" id="toc-simulation-2-stationary-ar1-with-zero-level" class="nav-link" data-scroll-target="#simulation-2-stationary-ar1-with-zero-level"><span class="header-section-number">8.2</span> Simulation 2: Stationary AR(1) with zero level</a></li>
  <li><a href="#simulation-2-stationary-ar1-with-non-zero-level" id="toc-simulation-2-stationary-ar1-with-non-zero-level" class="nav-link" data-scroll-target="#simulation-2-stationary-ar1-with-non-zero-level"><span class="header-section-number">8.3</span> Simulation 2: Stationary AR(1) with non-zero level</a></li>
  <li><a href="#simulation-3-stationary-ar1-with-trend" id="toc-simulation-3-stationary-ar1-with-trend" class="nav-link" data-scroll-target="#simulation-3-stationary-ar1-with-trend"><span class="header-section-number">8.4</span> Simulation 3 (Stationary AR(1) with trend)</a></li>
  <li><a href="#adf-test" id="toc-adf-test" class="nav-link" data-scroll-target="#adf-test"><span class="header-section-number">8.5</span> ADF-Test</a></li>
  <li><a href="#simulation-ar3" id="toc-simulation-ar3" class="nav-link" data-scroll-target="#simulation-ar3"><span class="header-section-number">8.6</span> Simulation: AR(3)</a></li>
  <li><a href="#kpss-test" id="toc-kpss-test" class="nav-link" data-scroll-target="#kpss-test"><span class="header-section-number">8.7</span> KPSS Test</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">DF-test</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Boyko Amarov </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 4, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="unit-root-tests" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Unit Root Tests</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("urca")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urca)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Random walk model without a drift</p>
<p><span class="math display">\[
\begin{align}
y_{t} = y_{t - 1} + e_{t}, e_t \sim WN(\sigma^2)\\
\Delta y_{t} = y_{t} - y_{t - 1} = e_{t}\\
f' = \lim_{\epsilon \to 0}\frac{f(x) - f(x + \epsilon)}{\epsilon}
\end{align}
\]</span> The solution of the characteristic equation of this model is equal to one. We say that <em>the equation has a unit root</em>.</p>
<p><span class="math display">\[
\lambda - 1 = 0 \implies \\
\lambda^* = 1
\]</span></p>
<p>The solution of this characteristic equation is 1. We say that the characteristic equation has a unit root.</p>
<p>ARIMA(0, 1, 0)</p>
<section id="random-walks-simulation" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="random-walks-simulation"><span class="header-section-number">7.1</span> Random Walks Simulation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>rw1 <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">model =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)), <span class="at">n =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>rw2 <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">model =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)), <span class="at">n =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># rw2 &lt;- 1.5 * rw1 + rnorm(n = 200)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(rw1, rw2),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">process =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">200</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="dv">2</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> y, <span class="at">color =</span> process)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>linreg_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(rw2 <span class="sc">~</span> rw1)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linreg_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rw2 ~ rw1)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.8944  -2.9879  -0.0065   3.8737  10.3704 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.4682     0.9624  -0.486    0.627    
rw1          -0.7219     0.1134  -6.364 1.34e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.924 on 198 degrees of freedom
Multiple R-squared:  0.1698,    Adjusted R-squared:  0.1656 
F-statistic:  40.5 on 1 and 198 DF,  p-value: 1.336e-09</code></pre>
</div>
</div>
<p>Regression model</p>
<p><span class="math display">\[
y_{t}: \text{ random walk 2} \\
x_{t}: \text{ random walk 1} \\
y_{t} = \beta_0 + \beta_1 x_{t} + u_{t}, u_{t} \sim N(0, \sigma^2)
\]</span></p>
<p>Estimated regression equation</p>
<p><span class="math display">\[
\hat{y}_{t} = 6.15 - 1.78 x_{t}
\]</span> T-Test of the hypothesis</p>
<p><span class="math display">\[
H_0: \beta_1 = 0\\
H_1: \beta_1 \neq 0
\]</span> We reject the null hypothesis if the p-value of the test is less than 0.05 (convention).</p>
<p>Spurious regression if y and x are unit-root processes.</p>
<p><span class="math display">\[
\hat{y}_{t} = -1.86 + 0.19 x_{t}
\]</span></p>
</section>
<section id="how-to-check-for-spurious-regression" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="how-to-check-for-spurious-regression"><span class="header-section-number">7.2</span> How to check for spurious regression?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(linreg_fit)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="unit-root-tests-1" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Unit root tests</h1>
<p>AR(1) process without a constant</p>
<p><span class="math display">\[
y_{t} = \phi_1 y_{t - 1} + e_{t}, e_t \sim WN(\sigma^2)
\]</span> If the process has a unit root, it follows that <span class="math inline">\(\phi_1 = 1\)</span>.</p>
<p>We would like to test the hypothesis:</p>
<p><span class="math display">\[
H_0: \phi_1 = 1\\
H_1: \phi_1 &lt; 1
\]</span></p>
<p>The first difference of the random walk process is stationary, because it is simply equal to the pure random process <span class="math inline">\(e_{t}\)</span> and it is stationary by the properties of the pure random process. We say that the process (in this case the random walk process) is integrated of order 1.</p>
<section id="dickey-fuller-unit-root-test" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="dickey-fuller-unit-root-test"><span class="header-section-number">8.1</span> Dickey-Fuller Unit Root Test</h2>
<p><span class="math display">\[
\begin{align}
y_{t} - y_{t - 1} = \phi_1 y_{t - 1} + e_{t} - y_{t - 1} \\
\iff\\
\Delta y_{t} = (\phi_1 - 1)y_{t - 1} + e_t
\end{align}
\]</span></p>
<p><span class="math display">\[
\phi_1 - 1 = 0 \iff \phi_1 = 1
\]</span></p>
<p>We can use the t-statistic for testing the hypothesis that the coefficient of <span class="math inline">\(y_{t - 1}\)</span> equals 0, but the distribution of this statistic under the <span class="math inline">\(H_0\)</span> (assuming that <span class="math inline">\(\phi_1 = 1\)</span>) is not a t-distribution. Therefore, we need to use special critical values in order to perform the test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(rw1, <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4319 -0.7968 -0.0641  0.6396  3.1853 

Coefficients:
         Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1 -0.003369   0.008315  -0.405    0.686

Residual standard error: 0.9943 on 198 degrees of freedom
Multiple R-squared:  0.0008286, Adjusted R-squared:  -0.004218 
F-statistic: 0.1642 on 1 and 198 DF,  p-value: 0.6858


Value of test-statistic is: -0.4052 

Critical values for test statistics: 
      1pct  5pct 10pct
tau1 -2.58 -1.95 -1.62</code></pre>
</div>
</div>
<p>-1 in the regression formula instructs lm to exclude the intercept from the regression equation.</p>
<p><span class="math display">\[
\underbrace{\Delta y_{t}}_{z.diff} = \underbrace{y_{t - 1}}_{z.lag.1} + e_t
\]</span> t-value is the value of the t-statistic.</p>
<p><span class="math display">\[
t = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)}
\]</span></p>
<p><span class="math display">\[
-0.007011 / 0.008509 = -0.824
\]</span> To perform the test, compare the t-value with the critical values:</p>
<pre><code>  1pct  5pct 10pct</code></pre>
<p>tau1 -2.58 -1.95 -1.62</p>
<p>and we reject the null hypothesis if the t-value value is lower than the critical values.</p>
<p>-0.824 &gt; -1.62 (the critical value corresponding to a 10% significance level), so we cannot reject the null hypothesis.</p>
<p><span class="math display">\[
H_0: \phi_1 - 1 = 0
\]</span></p>
</section>
<section id="simulation-2-stationary-ar1-with-zero-level" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="simulation-2-stationary-ar1-with-zero-level"><span class="header-section-number">8.2</span> Simulation 2: Stationary AR(1) with zero level</h2>
<p><span class="math display">\[
y_{t} = 0.7y_{t - 1} + e_{t}, e_t \sim WN(1)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5445</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ar1 <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n =</span> <span class="dv">200</span>, <span class="at">model =</span> <span class="fu">list</span>(<span class="at">ar =</span> <span class="fl">0.7</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ar1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar1, <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1957 -0.4637  0.1847  0.7274  2.8661 

Coefficients:
        Estimate Std. Error t value Pr(&gt;|t|)    
z.lag.1 -0.35559    0.05437   -6.54 5.12e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.981 on 198 degrees of freedom
Multiple R-squared:  0.1776,    Adjusted R-squared:  0.1735 
F-statistic: 42.77 on 1 and 198 DF,  p-value: 5.122e-10


Value of test-statistic is: -6.5401 

Critical values for test statistics: 
      1pct  5pct 10pct
tau1 -2.58 -1.95 -1.62</code></pre>
</div>
</div>
<p>-6.54 &lt; -2.58 &lt; -1.95 =&gt; reject the null hypothesis of presence of a unit root</p>
</section>
<section id="simulation-2-stationary-ar1-with-non-zero-level" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="simulation-2-stationary-ar1-with-non-zero-level"><span class="header-section-number">8.3</span> Simulation 2: Stationary AR(1) with non-zero level</h2>
<p><span class="math display">\[
y_{t} = 100 + 0.7y_{t - 1} + e_{t}, e_t \sim N(0, 1)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>ar2 <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">+</span> ar1</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ar2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar2, <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3897 -0.5694 -0.0054  0.6735  2.5924 

Coefficients:
          Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1 -4.129e-05  7.640e-04  -0.054    0.957

Residual standard error: 1.082 on 198 degrees of freedom
Multiple R-squared:  1.475e-05, Adjusted R-squared:  -0.005036 
F-statistic: 0.00292 on 1 and 198 DF,  p-value: 0.957


Value of test-statistic is: -0.054 

Critical values for test statistics: 
      1pct  5pct 10pct
tau1 -2.58 -1.95 -1.62</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar2, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.2327 -0.6111  0.0591  0.6185  2.7507 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 38.72772    5.64276   6.863 8.54e-11 ***
z.lag.1     -0.38589    0.05622  -6.863 8.53e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9742 on 197 degrees of freedom
Multiple R-squared:  0.193, Adjusted R-squared:  0.1889 
F-statistic: 47.11 on 1 and 197 DF,  p-value: 8.529e-11


Value of test-statistic is: -6.8635 23.554 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.46 -2.88 -2.57
phi1  6.52  4.63  3.81</code></pre>
</div>
</div>
<p>Compare the t-value (-6.253) to the critical values:</p>
<pre><code>  1pct  5pct 10pct</code></pre>
<p>tau2 -3.46 -2.88 -2.57</p>
<p>-6.253 &lt; -3.46 (1-percent critical value) =&gt; we reject the null hypothesis at a 1-percent significance level.</p>
</section>
<section id="simulation-3-stationary-ar1-with-trend" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="simulation-3-stationary-ar1-with-trend"><span class="header-section-number">8.4</span> Simulation 3 (Stationary AR(1) with trend)</h2>
<p><span class="math display">\[
y_{t} = 10 + 0.1t + 0.7 y_{t - 1} + e_{t}, e_t \sim N(0, 1)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ar3 <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">+</span> <span class="fl">0.1</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(ar1)) <span class="sc">+</span> ar1</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ar3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar3, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.4678 -0.5735  0.0574  0.6901  2.4643 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  0.48017    0.28721   1.672   0.0961 .
z.lag.1     -0.01859    0.01360  -1.367   0.1731  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.079 on 197 degrees of freedom
Multiple R-squared:  0.0094,    Adjusted R-squared:  0.004372 
F-statistic: 1.869 on 1 and 197 DF,  p-value: 0.1731


Value of test-statistic is: -1.3673 1.8173 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.46 -2.88 -2.57
phi1  6.52  4.63  3.81</code></pre>
</div>
</div>
<p>-0.9984 &gt; -2.57 =&gt; the test fails to reject the null hypothesis at any reasonable significance level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar3, <span class="at">type =</span> <span class="st">"trend"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.3040 -0.6054  0.0831  0.5956  2.6345 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.446414   0.632991   7.024 3.46e-11 ***
z.lag.1     -0.402536   0.057255  -7.031 3.34e-11 ***
tt           0.038493   0.005608   6.865 8.57e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9716 on 196 degrees of freedom
Multiple R-squared:  0.2014,    Adjusted R-squared:  0.1933 
F-statistic: 24.71 on 2 and 196 DF,  p-value: 2.681e-10


Value of test-statistic is: -7.0306 17.2027 24.7148 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -3.99 -3.43 -3.13
phi2  6.22  4.75  4.07
phi3  8.43  6.49  5.47</code></pre>
</div>
</div>
<pre><code>  1pct  5pct 10pct</code></pre>
<p>tau3 -3.99 -3.43 -3.13</p>
<p>-6.2976 &lt; -3.99 =&gt; reject the null hypothesis at a 1-percent significance level.</p>
</section>
<section id="adf-test" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="adf-test"><span class="header-section-number">8.5</span> ADF-Test</h2>
<p>Let us consider an AR(2) process</p>
<p><span class="math display">\[
y_{t} = \phi_1 y_{t - 1} + \phi_2 y_{t - 2} + e_t
\]</span></p>
<p>If this process has a unit root, then its characteristic equation</p>
<p><span class="math display">\[
\lambda ^2 - \phi_1 \lambda - \phi_2 = 0
\]</span></p>
<p>has a solution <span class="math inline">\(\lambda^{*} = 1\)</span>, therefore, setting <span class="math inline">\(\lambda = 1\)</span> satisfies the equation, and we obtain:</p>
<p><span class="math display">\[
1^2 - \phi_1 - \phi_2 = 0
\]</span></p>
<p>Therefore, if the process has a unit root, its coefficients sum to one. This is a hypothesis that we can test using data. Following the approach of the DF-Test, we can try to construct a regression equation where one of the coefficients is <span class="math inline">\(1 - \phi_1 - \phi_2\)</span>. Then we can conduct a test of the null hypothesis that this coefficient is zero.</p>
<p>It turns out that we can reparemetrize the AR(2) model to obtain such an equation:</p>
<p><span class="math display">\[
\begin{align}
y_{t} - y_{t - 1} &amp; = \phi_1 y_{t - 1} - y_{t - 1} + \phi_2 y_{t - 2} + e_t\\
\Delta y_{t} &amp; = (\phi_1 - 1)y_{t - 1} + \phi_2 y_{t - 2} + e_t\\
\Delta y_{t} &amp; = (\phi_1 - 1)y_{t - 1} + \phi_2 y_{t - 1} - \phi_2 y_{t - 1} + \phi_2 y_{t - 2} + e_t\\
\Delta y_{t} &amp; = (\phi_1 + \phi_2 - 1)y_{t - 1} - \phi_2 y_{t - 1} \phi_2 y_{t - 2} + e_t\\
\Delta y_{t} &amp; = (\phi_1 + \phi_2 - 1)y_{t - 1} - \phi_2(y_{t - 1} - y_{t - 2}) + e_t\\
\Delta y_{t} &amp; = (\phi_1 + \phi_2 - 1)y_{t - 1} - \phi_2\Delta y_{t - 1} + e_t\\
\end{align}
\]</span></p>
<p>In the general case of an AR(p) process the equation looks more complicated but it is derived in exactly the same way as for the AR(2) process:</p>
<p><span class="math display">\[
\Delta y_t = (\rho - 1) y_{t - 1} + \theta_{1} \Delta y_{t - 1} + \theta_2 \Delta y_{t - 2} + \ldots + \theta_{p - 1} \Delta y_{t - p + 1} + e_t
\]</span></p>
<p>where <span class="math inline">\(\rho\)</span> and <span class="math inline">\(\theta_i\)</span> are defined as:</p>
<p><span class="math display">\[
\rho = \sum_{j = 1}^p \alpha_j \\
\theta_i = - \sum_{j = i + 1}^{p} \alpha_j
\]</span> ## Information Criteria</p>
<p><span class="math display">\[
AIC = -2 \log(L) + 2(p + q + k + 1)
\]</span></p>
<p><span class="math display">\[
AICe = -2 \log(L) + 2(p + q + k + 1) + \frac{2(p + q + k + 1)(p + q + k + 2)}{T - p - q - k - 2}
\]</span></p>
</section>
<section id="simulation-ar3" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="simulation-ar3"><span class="header-section-number">8.6</span> Simulation: AR(3)</h2>
<p><span class="math display">\[
y_t = 0.6y_{t - 1} + 0.4y_{t - 2} - 0.7y_{t - 2} + e_t, e_t \sim N(0, 1)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">521</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ar4 <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n =</span> <span class="dv">200</span>, <span class="at">model =</span> <span class="fu">list</span>(<span class="at">ar =</span> <span class="fu">c</span>(<span class="fl">0.6</span>, <span class="fl">0.4</span>, <span class="sc">-</span><span class="fl">0.7</span>)))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ar4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06-Unit-Root-Tests_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar4, <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.2994 -0.9389 -0.1619  0.8093  4.0805 

Coefficients:
        Estimate Std. Error t value Pr(&gt;|t|)    
z.lag.1 -0.38591    0.05607  -6.883 7.54e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.302 on 198 degrees of freedom
Multiple R-squared:  0.1931,    Adjusted R-squared:  0.189 
F-statistic: 47.38 on 1 and 198 DF,  p-value: 7.543e-11


Value of test-statistic is: -6.8832 

Critical values for test statistics: 
      1pct  5pct 10pct
tau1 -2.58 -1.95 -1.62</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(ar4, <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.2490 -1.0398 -0.1433  0.7901  4.0562 

Coefficients:
           Estimate Std. Error t value Pr(&gt;|t|)    
z.lag.1    -0.44249    0.06223  -7.110 2.11e-11 ***
z.diff.lag  0.14540    0.07070   2.057   0.0411 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.294 on 196 degrees of freedom
Multiple R-squared:  0.2096,    Adjusted R-squared:  0.2016 
F-statistic: 25.99 on 2 and 196 DF,  p-value: 9.725e-11


Value of test-statistic is: -7.1101 

Critical values for test statistics: 
      1pct  5pct 10pct
tau1 -2.58 -1.95 -1.62</code></pre>
</div>
</div>
</section>
<section id="kpss-test" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="kpss-test"><span class="header-section-number">8.7</span> KPSS Test</h2>
<p>The KPSS test considers stationarity as the null hypothesis. Let’s consider the following process:</p>
<p><span class="math display">\[
y_t = \alpha_t + \beta t + e_t, e_t \sim WN(\sigma^2)
\]</span></p>
<p>where <span class="math inline">\(\alpha_t\)</span> is a random walk process: <span class="math inline">\(\alpha_t = \alpha_{t - 1} + \epsilon_t\)</span>. If <span class="math inline">\(y_t\)</span> is trend-stationary (i.e.&nbsp;has no unit roots), then the variance of <span class="math inline">\(\epsilon_t\)</span> is zero (i.e.&nbsp;<span class="math inline">\(\alpha_t\)</span> is a constant process).</p>
<p>With the KPSS test we reject the null hypothesis (trend-stationarity) for <em>large</em> values of the test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(rw1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: mu with 4 lags. 

Value of test-statistic is: 1.7958 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.347 0.463  0.574 0.739</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(ar1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: mu with 4 lags. 

Value of test-statistic is: 0.398 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.347 0.463  0.574 0.739</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-Model-Fitting.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ARIMA Modeling (1)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-ARIMA-Forecasting.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Forecasting ARIMA processes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>